site_name: DynareJulia User Guide
theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Installation: installation.md
  - Video Tutorials: video-tutorials.md
  - Simple Model: simple-model.md
  - ENDOCRED: endocred.md
  - GIMF: gimf.md
  - Potential Errors: potential-errors.md   
  - FAQ: faq.md