site_name: DynareJulia User Guide
theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Installation: installation.md
  - Basic Usage: basic-usage.md
  - Advanced Usage: advanced-usage.md
  - Examples: examples.md
  - FAQ: faq.md